version: "3.8"
services:
  neo4j:
    image: neo4j:latest
    container_name: neo4j
    ports:
      - 7474:7474
      - 7687:7687
    volumes:
      - /home/uminho/dockers/data/neo4j/data:/data
    environment:
      - NEO4J_AUTH=neo4j/password
    restart: always

  mongodb:
    container_name: mongo_db
    image: mongo
    volumes:
      - /home/uminho/dockers/data/mongodb/:/data/db
    ports:
      - "27017:27017"
    restart: always

  oracle-xe:
    container_name: oracle-xe
    image: gvenzl/oracle-xe
    ports:
      - "1521:1521"
    environment:
      - ORACLE_PASSWORD=pass
    restart: always
